spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3308/scheduling?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # 建表的时候，将默认的存储引擎切换为 InnoDB 默认为MyISAM
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      # create ----每次运行该程序，没有表格会新建表格，表内有数据会清空；
      # create-drop ----每次程序结束的时候会清空表
      # update ---- 每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新 如果model类新增了一个字段 表也会自动添加一个字段
      # validate ---- 运行程序会校验数据与数据库的字段类型是否相同，不同会报错。
      ddl-auto: update
    database: mysql
  jackson:
    time-zone: GMT+8